### ISSUE TITLE
M/T problem

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#281]
When I turn off the music [M] in the options and press [T], the game freezes and closes the window

![image](https://user-images.githubusercontent.com/2237225/213538516-e65dbd57-fca0-4878-a04c-05a0d395417d.png)

**Comment by tlongstretch** [comment]
Good catch, I get same hang also.  That means it should be easy for me to fix.

**Comment by tlongstretch** [comment]
fixed in unstable
