### ISSUE TITLE
separate Viewport zoom from UI element zoom

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#282]
![image](https://user-images.githubusercontent.com/2237225/213539238-ffdcf3f8-5854-4fe9-b6e7-c9a7ea1d0210.png)

**Comment by zdechlak** [comment]
https://user-images.githubusercontent.com/2237225/213541647-e830e71f-95b3-4f02-8e3a-48fbeaab105f.mp4

**Comment by tlongstretch** [comment]
That is actually the intended behavior from Freeserf.  I have thought about making panelbar & popup zoom a separate control as I don't really like it either, but it seems that some people may prefer it.  I will mark this as feature request.

Note that the cut-off-right-half-of-panel on the Options screen shown in your last frame is a known but, I need to create Issue tracker for at some point.  This is due to the flip between Large and Normal popup window types

**Comment by zdechlak** [comment]
it would be great if it worked like in this project https://www.simpleguide.net/sg/serflings.jsf

join forces guys

**Comment by tlongstretch** [comment]
The creator of Serflings is not willing to open source his project, unfortunately.

**Comment by tlongstretch** [comment]
I looked into this briefly but it is not a simple fix.  The GUI objects are all children to the Viewport game window and they all scale together.  I need to break them apart to be drawn totally separately.

**Comment by tlongstretch** [comment]
Looking at this further, it looks like the code is scaling the entire frame and not individual objects, and the core SDL2 library doesn't actually support zooming individual sprites.  I am looking into the SDL_gfx supplemental library to see if is possible to scale the Viewport without scaling the entire frame, and then draw normal unscaled UI objects on top of it

**Comment by tlongstretch** [comment]
looks like using RenderCopyEx to draw the zoomed/reduced current frame so far, after terrain and game objects drawn but before UI elements drawn, with a dsrect of the full game window size, then draw UI elements on top?  Is it possible to call RenderCopy / RenderCopyEx multiple times per Frame?  I would think so.. I suspect it is calling every single time it draws a sprite...

https://stackoverflow.com/questions/328500/proper-way-to-scale-an-sdl-surface-without-clipping


it maybe be simpler (or ultimately the same thing) to draw all non-UI sprites multiplied by zoom_factor (using RenderCopyEx?) and draw UI sprites normally.  Only complication is trying to reclaim the performance benefit of not drawing anything that can't be seen, which the current implementation does (I'm pretty sure), though the perf hit might not be all that important...

**Comment by tlongstretch** [comment]
this is mostly working now!  it was difficult to separate the Viewport from the rest of the UI but it is now working and popup-dragging while zoom is now supported.   Still need to tweak some things as the viewport jumps around when things resized/opened/closed, but the zoom part works well.

https://user-images.githubusercontent.com/45954803/218240779-bcc7f374-8747-4322-ab26-9fa41aa79c35.mp4

**Comment by tlongstretch** [comment]
fixing the jumpiness turned out to be easy, and I made it so popups that become off-screen due to resizing are simply moved back on-screen.  This seems like it all works great now, but haven't playtested

**Comment by tlongstretch** [comment]
done in v0.6.1
