### ISSUE TITLE
I can't build houses here

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#284]
https://user-images.githubusercontent.com/2237225/213571277-af9aca13-2b94-474f-99f7-cd84f6486011.mp4

[icantbulid.zip](https://github.com/forkserf/forkserf/files/10461443/icantbulid.zip)

**Comment by tlongstretch** [comment]
this is very interesting, I will try to reproduce, thank you

**Comment by tlongstretch** [comment]
fixed in unstable, thank you for providing save and video to reproduce.  

Cause was faulty logic in the effort to restore the original game behavior of disallowing buildings to be placed where their flag would touch water.  

changed this:
```
Game::can_build_small(MapPos pos) const {
  // Freeserf was missing the original game check preventing buildings from being placed
  //  with its flag pos touching edge of water
  if (!map_types_within(map->move_down_right(pos), Map::TerrainGrass0, Map::TerrainGrass3)){
    return false;
  }
```

to this:
```
Game::can_build_small(MapPos pos) const {
  // Freeserf was missing the original game check preventing buildings from being placed
  //  with its flag pos touching edge of water
  if (!map_types_within(map->move_down_right(pos), Map::TerrainGrass0, Map::TerrainSnow1)){
    return false;
  }
```
