### ISSUE TITLE
sending geologists can crash the game

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#285]
sending geologists can crash the game
another mistake - the geologist leaves and immediately returns to the castle

https://user-images.githubusercontent.com/2237225/213578812-aadf64f9-1a09-469b-a190-caf33865b006.mp4

the video stops when the game freezes

**Comment by tlongstretch** [comment]
Ah, yes this was probably never tested.  In the original game it shows a "Requested Building" popup instead of the Transport Info popup while the castle is not yet constructed.  I will fix this

**Comment by tlongstretch** [comment]
My above explanation is wrong, but this is now fixed in unstable branch and matches original game behavior.  If you do this now, a geologist will walk out of the castle to the flag then walk right back in, matching original game.

**Comment by zdechlak** [comment]
yesterday when I was looking (today I don't have time) the geologist doesn't reach the flag at all [0.5.2]
