### ISSUE TITLE
the minimap closes when clicked

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#295]
this makes it difficult to navigate the map
it closes when I release the mouse button

https://user-images.githubusercontent.com/2237225/213940500-d9b5cb33-4cc9-40f4-984f-74be5ed249a7.mp4

**Comment by tlongstretch** [comment]
This seems to be how the original game worked, I just verified with Settlers1 in DosBox.  However, I agree with you that it would be nice to be able to keep it open, especially since windows can now be easily closed by right-clicking when desired.  Adding as feature request

**Comment by zdechlak** [comment]
here the problem is different - it's not that the minimap turns off when I mark a point on it

it turns off when I move it with the right mouse button and release it

**Comment by tlongstretch** [comment]
I have pushed change that keeps the minimap open when left-clicking, also the minimap now updates if you scroll the game window behind it around.  

The second thing you mention..  I have set right-click to close any active popup window, including the minimap.  Can you instead scroll by dragging left or center/wheel mouse button?  These will not result in closing minimap

**Comment by zdechlak** [comment]
works with the left mouse button

**Comment by tlongstretch** [comment]
I prefer the "right click closes popup" functionality over being able to right click on minimap, but I'm willing to reconsider this in the future
