### ISSUE TITLE
winning suspends the game

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#297]
winning suspends the game
the castle is not burning the game freezes

I guess that also applies to enemy warehouses

[f1.zip](https://github.com/forkserf/forkserf/files/10482164/f1.zip)

**Comment by tlongstretch** [comment]
needed a nullptr checked, fix in unstable.  

What is supposed to happen when you "win"?  Or when a player is eliminated?  I always quit the game once it was clear that I would win.  

Do the enemy's buildings all burn when their last castle/stock is destroyed?  

I see there are some "AI player losing" graphics, and some "Human Player winning/losing" type graphics in the data files

**Comment by zdechlak** [comment]
_Do the enemy's buildings all burn when their last castle/stock is destroyed?_ 

When the castle is burning, buildings are burning just like when we capture the guardhouse
You can play without a castle if you have warehouses 

In addition, by playing missions in the original Settlers, graphics appeared depending on what opponent we defeated
all games also had common victory graphics (those for generated maps)

![image](https://user-images.githubusercontent.com/2237225/214210687-2723e40d-2037-463d-bd36-714e3f1ed918.png)

your game has this problem that after burning the castle the game freezes and turns off

**Comment by zdechlak** [comment]
the castle is on fire and the fun continues
https://user-images.githubusercontent.com/2237225/214212424-a774a181-eda4-48e4-8a1a-0ef4931d8c3c.mp4

**Comment by tlongstretch** [comment]
this no longer crashes the game, I have seen a 4x AIs game result in an AI destroying the others' castles and game continues.  I would like to implement some kind of winning graphics when this happens but need to think about details more
