### ISSUE TITLE
the game pauses itself

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#299]
the game pauses itself

The game pauses every now and then - I have to press P to continue playing

[pause.zip](https://github.com/forkserf/forkserf/files/10494656/pause.zip)

**Comment by tlongstretch** [comment]
This is because some error condition was detected, to assist debugging.  I usually take these out before pushing a release but I must have missed one

**Comment by tlongstretch** [comment]
removed pause-debugging in v0.5.3
