### ISSUE TITLE
trees on the water

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#303]
![image](https://user-images.githubusercontent.com/2237225/215218167-5098f0e5-4c97-491f-add2-ff2c9c7b29a9.png)
[treee.zip](https://github.com/forkserf/forkserf/files/10523574/treee.zip)

**Comment by tlongstretch** [comment]
must be something wrong with the new cattail graphics, the Trees are the fallback sprite when it can't find the correct one.  Here is what I see with that same area of your save:

![forkserf_tree_cattail_issue](https://user-images.githubusercontent.com/45954803/215226779-097bfe9a-ff01-4046-af36-063b4c60f2b6.png)


I probably packaged something wrongly, looking.   Meanwhile, you can disable the Cattails/Reeds slider in the Map Generator options to avoid this for future games on same v0.5.3

**Comment by tlongstretch** [comment]
I had forgotten the SDL2_image in the windows build, fixed now, try updated version here https://github.com/forkserf/forkserf/releases/download/v0.5.3/Forkserf-0.5.3-Win64.zip
