### ISSUE TITLE
middle mouse button clicking on the map icon

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#310]
middle mouse button on the map icon should take us to the castle (its location on the map)

https://user-images.githubusercontent.com/2237225/216635397-44c38cda-95f4-4df6-a06b-806ae127a0b7.mp4

![image](https://user-images.githubusercontent.com/2237225/216627589-7d0ac644-3d70-46a5-b6d5-c9b8739d22c3.png)

**Comment by tlongstretch** [comment]
I didn't know that was a normal feature of the original game, good to know.  This should be simple to implement

**Comment by tlongstretch** [comment]
this is implemented in unstable branch
