### ISSUE TITLE
first weird error in trying to build a route from A to Z

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#311]
first weird error in trying to build a route from A to Z

![image](https://user-images.githubusercontent.com/2237225/216629107-effebe57-f1de-40db-846f-a600deec2f24.png)
![image](https://user-images.githubusercontent.com/2237225/216629455-ef7284ae-5625-4573-a7b7-e6f7ab1d76a5.png)
![image](https://user-images.githubusercontent.com/2237225/216629715-2e15501f-be4f-4601-a20c-df853eec1787.png)

[double-click-a-z.zip](https://github.com/forkserf/forkserf/files/10579787/double-click-a-z.zip)

**Comment by tlongstretch** [comment]
yes this looks like a bug, it seems any place the water is only a single triangle wide the game is showing it as valid for land path.  I see same behavior in the water area a bit to the right of your screenshot in the savegame you provided.   Will fix

**Comment by tlongstretch** [comment]
fixed in unstable, created new map function that determines if a path crosses even a single water tile
