### ISSUE TITLE
panel disappears and the zoom does not work

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#312]
sometimes the panel disappears and the zoom does not work, it helps if I press F10 and close this window

![image](https://user-images.githubusercontent.com/2237225/216630273-ceff76d8-3b51-4d74-87ab-91fcefe70764.png)

**Comment by tlongstretch** [comment]
does this happen when moving/resizing the game window?  while zooming?  randomly?  I have never seen this issue myself

**Comment by zdechlak** [comment]
it seems to me that it appears when I minimize the game and enter, for example, google chrome - but not always

I'll actually be watching it

**Comment by zdechlak** [comment]
this probably happens when the mother turns on the TV that is connected to the HDMI on the computer 
then it resets my nvidia display driver for a while

**Comment by tlongstretch** [comment]
I was able to reproduce this on v0.6.0, but it appears to be fixed in new unstable release using new zoom method
