### ISSUE TITLE
reset the settings to default with one button

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#317]
Is it possible to reset the settings to default with one button?

![image](https://user-images.githubusercontent.com/2237225/216862845-836d73a9-9c3d-413f-b16f-5d226c0b6eb1.png)

**Comment by tlongstretch** [comment]
added in unstable

**Comment by zdechlak** [comment]
make me a bulid windows 64bit version with corrections, because I can't 
I can't (it'd be nice if you made me this program to extract sprites too) :P
