### ISSUE TITLE
build possibliities special click not working when button is available?

### ISSUE THREAD

**Issue by tlongstretch** [forkserf/forkserf#320]

**Comment by zdechlak** [comment]
sir please make this a priority issue

https://user-images.githubusercontent.com/2237225/217996027-c73e9928-45e5-48b9-a2eb-ace671d4fa94.mp4

**Comment by zdechlak** [comment]
double click stopped working (turn on the sound to hear the clicking) 
0.6 version

https://user-images.githubusercontent.com/2237225/217996492-a847bce2-4c13-440d-8420-3b26febd6c6c.mp4

**Comment by zdechlak** [comment]
in the game you should use the left mouse button to place buildings and build roads

https://user-images.githubusercontent.com/2237225/218320578-c10e0722-f693-4d21-87c0-c5e1da98edef.mp4

**Comment by tlongstretch** [comment]
build possibilities button special-click fixed now
