### ISSUE TITLE
add option - disable demolition confirmation messages

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#323]
add option - disable demolition confirmation messages

![image](https://user-images.githubusercontent.com/2237225/217998218-f32309de-b066-4e1d-88a1-af5c116c1780.png)

**Comment by tlongstretch** [comment]
Yes, also the "are you sure you want to quit?" message.

**Comment by tlongstretch** [comment]
instead, for now I have made it so that special-clicking (double, L+R, or right) on the demolish button skips the confirmation
