### ISSUE TITLE
0.61 notification popups incorrectly scaling with Viewport and move off-screen

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#328]
![image](https://user-images.githubusercontent.com/2237225/218287414-824f71ea-3ce7-404d-9294-4a9d3e0a74aa.png)

no message notifications
after clicking on the white flashing message - no information appears about what it concerns

this window is gone

screenshot from version 6.0 in 6.1 this window is missing
![image](https://user-images.githubusercontent.com/2237225/218287424-695907b5-c34d-4a4e-b357-d642fcc5787d.png)

**Comment by zdechlak** [comment]
update - this window disappears when using zoom

https://user-images.githubusercontent.com/2237225/218291012-06377ccb-b4f9-47c1-84a5-6232bc1185d6.mp4

**Comment by tlongstretch** [comment]
I will investigate.  I never use the notifications myself so I didn't notice they were broken

**Comment by zdechlak** [comment]
the F10 window does not display properly

https://user-images.githubusercontent.com/2237225/218320787-806a57a1-c495-4aec-a196-d2d305c69b0b.mp4

**Comment by tlongstretch** [comment]
"the F10 window does not display properly"
this is now fixed in unstable branch.  

Will look at notification issue soon

**Comment by tlongstretch** [comment]
I see what you mean about the notification popups, they are being drawn as part of the Viewport and not the unscaled UI layer, I need to move them to the UI layer so they are unscaled and centered properly

**Comment by tlongstretch** [comment]
notification popups fixed in unstable
