### ISSUE TITLE
first game crash in a long time

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#329]
0.61
![image](https://user-images.githubusercontent.com/2237225/218287674-52dc4e8c-11af-4686-ab00-e0b1d32da9eb.png)

**Comment by zdechlak** [comment]
when i try to throw a soldier into the water (interrupting the road) the game crashes

![image](https://user-images.githubusercontent.com/2237225/218290694-e58c95f9-0b36-4ac4-a723-251c35ce6324.png)

**Comment by tlongstretch** [comment]
Any Warn or Error message at the end of the console.txt or ai_PlayerX.txt logs that may explain?

For serfs in boats, this is known to be buggy.  I will spend some time debugging soon.

**Comment by zdechlak** [comment]
I played again later, a few hours until the morning and I did not encounter a bug, I will analyze

_Any Warn or Error message at the end of the console.txt or ai_PlayerX.txt logs that may explain?_

I don't have it unfortunately, but I'll download it if there's an error

**Comment by tlongstretch** [comment]
The game should write to these files in the game working directory, so if you get a crash there may be some useful info at the end of the log.  The logs are overwritten each time the game is started, though, so they will be lost if you don't capture the data first

**Comment by tlongstretch** [comment]
closing this for now, but feel free to re-open or open new if you see this again
