### ISSUE TITLE
update the mine  efficiency to show the actual samples over time

### ISSUE THREAD

**Issue by tlongstretch** [forkserf/forkserf#334]
the mining efficiency is based on the number of success/failures over time which is tracked as bits in an integer, it would be nice to show the actual values as some kind of histogram

**Comment by tlongstretch** [comment]
done in unstable, I like the way it came out

![forkserf_mining_output_indicator](https://user-images.githubusercontent.com/45954803/218917472-c081e94f-c507-4c33-a5ed-e52d8c624ce3.png)

**Comment by zdechlak** [comment]
add infinite resources option in options panel ✌️

**Comment by tlongstretch** [comment]
infinite as in mines always succeed 100% even if no resources found in ground??

**Comment by tlongstretch** [comment]
btw, loaded games won't immediately show the mining history because it relies on re-use of another variable, but it should work in future saves made by this version of the game and of course new games

**Comment by tlongstretch** [comment]
included in v0.6.2
