### ISSUE TITLE
havea keyboard key to cycle through mines

### ISSUE THREAD

**Issue by tlongstretch** [forkserf/forkserf#335]
now I am seeing the value in this... notifications are annoying so I tend to turn them off, but being able to occassionally check all mines for expiry by cycling through them with a keyboard key would be convenient...

**Comment by zdechlak** [comment]
make your choice in options panel / percentage indicator / new indicator

**Comment by tlongstretch** [comment]
done in unstable, the 'i' key will cycle through player's mines
