### ISSUE TITLE
it doesn't work as it should, it's worse than before

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#351]
https://user-images.githubusercontent.com/2237225/221097735-b20ab5dc-a73a-4d77-ab9b-30822bcba12f.mp4

there are problems with the panels, with the map, with hitting the buttons, etc.

**Comment by tlongstretch** [comment]
Can you explain with a bit more detail?  I am not seeing the problem in your video and the minimap works properly for me.

I do see some issues with special-clicking on panelbar not working when zoomed, which is now fixed in unstable branch.

**Comment by zdechlak** [comment]
I recorded here that jumping on the map does not work - but now when I started the game it works, it seems that it is a matter of zoom, in some close -ups it stops working

**Comment by tlongstretch** [comment]
ah, yes I discovered a few issues where UI elements don't work while zoomed.  I believe all are fixed now, I need to merge and publish the current code

**Comment by tlongstretch** [comment]
fixed in unstable
